### ISSUE TITLE
Notes field

### ISSUE THREAD

**Issue by ars1979** [webyaml/sites#1]
I do not believe there is a note field in the task table.
terminal output
Form validates
(1054, "Unknown column 'note' in 'field list'", None)
Cache:
{'url': u'http://localhost:8080/task/view/1', 'path': u'/task/view/1', 'rurl': 'http://localhost:8080/task/view/1'}

**Comment by webyaml** [comment]
The missing field 'note' should be of the type text.  The sql file will be updated shortly.  In the meantime you can add the field in a utility such as phpMyAdmin or run the following SQL statement:  

ALTER TABLE `task` ADD COLUMN `note` text NOT NULL AFTER `activity`;

**Comment by webyaml** [comment]
The change has been made to the file.  Thanks for finding the mistake.
